name: Yugi.vn
favicon: null
layout_spectrum: 0
typography_spectrum: 0.8061225
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FEFEFE'
    - '#554572'
    - '#C8C8C8'
    - '#E5FC00'
    - '#A9B526'
  brandStrength: 0.8694951
  lightness: 0.0718797
  saturation: 0.2969925
  rhythmicContrast: 0.7427498
purpose: []
